version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modular_data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      # Compose a PostgreSQL connection string for SQLAlchemy
      DATABASE_URL: postgres://postgres:postgres@db:5432/modular_data
      ADMIN_API_KEY: change_me
    ports:
      - "8000:8000"
    # Restart always to handle crashes
    restart: always

volumes:
  db_data: